FROM python:3.9.16-alpine

USER root

RUN apk add --update \
    tzdata

RUN cd /usr/share/zoneinfo
RUN cp /usr/share/zoneinfo/America/Bogota /etc/localtime

WORKDIR /usr/src/drogueria

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip
RUN apk add --no-cache jpeg-dev zlib-dev
RUN apk add --no-cache --virtual .build-deps build-base linux-headers \
    && pip install Pillow
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .

COPY . .

ENTRYPOINT ["/usr/src/drogueria/entrypoint.sh"]
