# Generated by Django 4.2.1 on 2023-05-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('imagen', models.CharField(max_length=250, verbose_name='Ruta imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descuento', models.IntegerField(blank=True, null=True, verbose_name='descuento')),
                ('activo', models.BooleanField(verbose_name='Producto activo')),
                ('descuento_activo', models.BooleanField(verbose_name='Descuento activo')),
                ('categoria', models.ManyToManyField(blank=True, null=True, to='productos.categorias', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
